### ISSUE TITLE
Conditional logic + accordion

### ISSUE THREAD

**Issue by ajolo2ky** [bvdr/acf-accordion#4]
Hi !

Currently if there's a logic condition between fields under different accordions they are not following it.

I'm using ACF 5.3.2.2
Thanks

**Comment by tmconnect** [comment]
This is how ACF conditional logic works. Both fields of the conditional logic (the field with the conditional logic and the field that holds the value for the logic) must be placed in the same element in the DOM.

Because Accordions are differ ten DOM elements the conditional logic can't work. It's the same if you are using tabs.

Hope this helps.
